import { z } from "zod";
import { router, publicProcedure } from "@/lib/trpc/init";

const news = [
  {
    id: 1,
    title: "Recognized on California Nonprofits Day: 20,000+ Meals, 8+ Campuses",
    slug: "california-nonprofits-day-recognition-2026",
    shortDesc: "WFM was celebrated on California Nonprofits Day for serving 20,000+ meals across 8+ Bay Area campuses — a milestone driven entirely by community support.",
    imagePath: "/images/resources/FS20251112TCWorldFoodMovementDeAnzaGFX100S00093.jpg",
    category: "Recognition",
    publishDate: new Date("2026-05-20"),
    metaTitle: null,
    metaDescription: null,
    content: `<p>On California Nonprofits Day 2026, the World Food Movement was celebrated for a milestone that would have seemed ambitious just 16 months ago: 20,000+ meals served to 4,000+ students across 8+ Bay Area campuses.</p><p>From De Anza to Evergreen Valley, from Chabot to Las Positas — every campus, every meal, every dollar came from a community that decided student hunger was solvable. Thank you to every donor, volunteer, and campus partner who made this possible.</p><p>Our goal for this academic year: 25,000+ meals. We're on track.</p>`,
  },
  {
    id: 2,
    title: "Evergreen Valley College Pilot: 700 Meals, 400+ Students Served",
    slug: "evergreen-valley-college-pilot-2026",
    shortDesc: "Our pilot program at Evergreen Valley College in San Jose has already reached 700 meals served to over 400 students — and it's just getting started.",
    imagePath: "/images/resources/IMG_2970.jpeg",
    category: "Campus News",
    publishDate: new Date("2026-05-15"),
    metaTitle: null,
    metaDescription: null,
    content: `<p>The World Food Movement's pilot program at Evergreen Valley College in San Jose has hit a meaningful early milestone: 700 meals served to more than 400 students.</p><p>For a program still in its early stages on campus, this level of uptake reflects just how real food insecurity is for Bay Area community college students. In Silicon Valley — one of the wealthiest regions in the world — students are still skipping meals to make rent.</p><p>WFM is proud to be at Evergreen Valley College and committed to growing the program to meet the full need on campus.</p>`,
  },
  {
    id: 3,
    title: "Ohlone College Students Now Receiving Free Hot Meals Weekly",
    slug: "ohlone-college-hot-meals-program-2026",
    shortDesc: "Fresh, hot plant-based meals are now being distributed weekly to students at Ohlone College in Fremont — no sign-up barriers, no stigma.",
    imagePath: "/images/resources/IMG_2881b.jpeg",
    category: "Campus News",
    publishDate: new Date("2026-05-10"),
    metaTitle: null,
    metaDescription: null,
    content: `<p>Students at Ohlone College in Fremont are now receiving fresh, hot plant-based meals through the World Food Movement's weekly distribution program. Charles Sasaki, President of Ohlone College, was among the leaders who helped launch WFM in the Bay Area at the March 2025 grand launch event.</p><p>The Ohlone program is part of WFM's commitment to serving every campus in our network with the same consistency and dignity: freshly cooked meals, distributed without paperwork, income checks, or stigma.</p>`,
  },
  {
    id: 4,
    title: "20,000 Meals Served Across Bay Area — and We're Just Getting Started",
    slug: "wfm-20000-meals-milestone-2026",
    shortDesc: "From 30 students at our De Anza launch to 20,000+ meals served across 8 Bay Area campuses — a milestone worth celebrating.",
    imagePath: "/images/resources/FS20251112TCWorldFoodMovementDeAnzaGFX100S00093.jpg",
    category: "Milestone",
    publishDate: new Date("2026-01-22"),
    metaTitle: null,
    metaDescription: null,
    content: `<p>One year ago, on January 22, 2025, we served our first meal at De Anza College in Cupertino. Thirty students showed up. By the end of that first week, hundreds had registered.</p><p>Today, we have served over 20,000 meals to more than 4,000 students across 8 Bay Area campuses — De Anza, Foothill, West Valley, Chabot, Ohlone, Las Positas, Evergreen Valley, and Mission College. Every meal costs $8. Every dollar came from donors who believed no student should go hungry.</p><p>Our goal: 1 million meals by 2030. We are on our way. Thank you for making this possible.</p>`,
  },
  {
    id: 5,
    title: "Foothill College Joins WFM as Our Newest Bay Area Partner",
    slug: "foothill-college-joins-wfm-march-2026",
    shortDesc: "Los Altos Hills-based Foothill College is now a WFM partner campus, bringing free hot meals to thousands more Bay Area students.",
    imagePath: "/images/resources/IMG_2960.jpeg",
    category: "Campus News",
    publishDate: new Date("2026-03-02"),
    metaTitle: null,
    metaDescription: null,
    content: `<p>On March 2, 2026, Foothill College in Los Altos Hills officially joined the World Food Movement as a partner campus. Students at Foothill can now register through the WFM app and collect freshly cooked, plant-based meals at their campus distribution point — no paperwork, no income verification, no stigma.</p><p>Foothill joins De Anza, Chabot, Ohlone, Las Positas, West Valley, Evergreen Valley, and Mission College in our growing Bay Area network.</p>`,
  },
  {
    id: 6,
    title: "10,000 Meals: Bay Area Officials Celebrate WFM Milestone",
    slug: "wfm-10000-meals-milestone-bay-area-2025",
    shortDesc: "California Assembly Member Alex Lee, Santa Clara County Supervisor Otto Lee, and college presidents gathered to mark 10,000 meals served.",
    imagePath: "/images/resources/IMG_2937.jpeg",
    category: "Milestone",
    publishDate: new Date("2025-11-15"),
    metaTitle: null,
    metaDescription: null,
    content: `<p>The World Food Movement celebrated a major milestone in November 2025: 10,000 meals served to Bay Area college students since our January launch.</p><p>The celebration drew California Assembly Member Alex Lee, Santa Clara County Supervisor Otto Lee, and college presidents from across the region — including Dr. Dyrell Foster of Las Positas College.</p><p>"Congratulations to the World Food Movement for reaching 10,000 meals served to hungry students in our home area," said Assembly Member Alex Lee. "I wish you a lot of luck in getting to your next milestone of a million meals."</p><p>Supervisor Otto Lee added: "This is absolutely crucial to make sure that no students are ever left hungry."</p>`,
  },
  {
    id: 7,
    title: "WFM Grand Launch: 200+ Leaders Gather in the Bay Area",
    slug: "wfm-grand-launch-bay-area-march-2025",
    shortDesc: "On March 8, 2025, over 200 educators, officials, and community leaders gathered to officially launch the World Food Movement in America.",
    imagePath: "/images/resources/IMG_2881b.jpeg",
    category: "Event",
    publishDate: new Date("2025-03-08"),
    metaTitle: null,
    metaDescription: null,
    content: `<p>On March 8, 2025, the World Food Movement held its grand launch event in the Bay Area, bringing together over 200 guests — including college presidents, elected officials, business leaders, and community advocates.</p><p>Dr. Omar Torres, President of De Anza College, delivered a powerful keynote. Charles Sasaki, President of Ohlone College, led the official launch. Cupertino Mayor Liang Chao and Milpitas Vice Mayor Garry Barbadillo joined for the WFM logo unveiling.</p><p>"I cannot think of a more critical time in our nation's history where this support for our students is so pivotal," said Dr. Torres.</p>`,
  },
  {
    id: 8,
    title: "First Meal Served at De Anza College — January 22, 2025",
    slug: "first-meal-de-anza-college-january-2025",
    shortDesc: "The movement started with 30 students and a simple idea: no student should go hungry. Here's how it began.",
    imagePath: "/images/resources/FullSize20250122TCSattvicMealsChelseaChangReleaseKickoff028572.jpg",
    category: "Milestone",
    publishDate: new Date("2025-01-22"),
    metaTitle: null,
    metaDescription: null,
    content: `<p>On January 22, 2025, the World Food Movement served its very first meal at De Anza College in Cupertino, California. It was a quiet start — 30 students, a small distribution table, and a big idea.</p><p>Within a week, hundreds of students had registered. Within a month, the program was operating multiple days per week. By spring, WFM had expanded to additional Bay Area campuses.</p><p>47% of California community college students experience food insecurity. The first meal at De Anza was our answer to that statistic. Every meal since has been a step toward our goal of 1 million meals by 2030.</p>`,
  },
];

export const newsRouter = router({
  list: publicProcedure.query(() => news.map(({ content: _c, ...n }) => n)),
  getBySlug: publicProcedure
    .input(z.object({ slug: z.string() }))
    .query(({ input }) => news.find((n) => n.slug === input.slug) ?? null),
});
